export const ADD_EXPENSE = "ADD_EXPENSE";
export const ADD_EXPENSE_FAIL = "ADD_EXPENSE_FAIL";
export const GET_EXPENSES = "GET_EXPENSES";
export const GET_EXPENSES_FAIL = "GET_EXPENSES_FAIL";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const DELETE_EXPENSE_FAIL = "DELETE_EXPENSE_FAIL";
export const EDIT_EXPENSE = "EDIT_EXPENSE";
export const EDIT_EXPENSE_FAIL = "EDIT_EXPENSE_FAIL";
